### ISSUE TITLE
not supported firefox quantam tested

### ISSUE THREAD

**Issue by santhosh77h** [VikLiegostaiev/react-page-scroller#1]
`wheelScroll` method in this source code is dependent on `event.wheelDeltaY` but that value is always `undefined` faced this problem only in firefox 

Because of this user was not able to move `scrollWindowUp`

**Comment by santhosh77h** [comment]
since the source code dependent on  `event.wheelDeltaY` but it is not supported instead of that anyone can use `event.deltaY`

**Comment by VikLiegostaiev** [comment]
Hi, thanks for your attention. It has been fixed.
