### ISSUE TITLE
[Feature Request] option to set intial page

### ISSUE THREAD

**Issue by xididri** [VikLiegostaiev/react-page-scroller#10]
It would be nice to have a prop to set the inital page. I am using redux to manage app state and calling goToPage on load fails.

**Comment by VikLiegostaiev** [comment]
Hi, @monkeydri. Yes, sure, I'll add it

**Comment by VikLiegostaiev** [comment]
Hi @didrip , can u try with `customPageNumber ` prop? does it fit u?

**Comment by VikLiegostaiev** [comment]
Closing this due to lack of response
