### ISSUE TITLE
[feature-request] option for responsive page (not 100% height)

### ISSUE THREAD

**Issue by xididri** [VikLiegostaiev/react-page-scroller#13]
It would be nice to have an option for page that don't require to be full height, ex headers and footers, similarly to what fullpage.js provides.

**Comment by VikLiegostaiev** [comment]
hi @monkeydri , is this what you want? https://vikliegostaiev.github.io/react-page-scroller/#/demos/contain

**Comment by monkeydri** [comment]
Not really, I need to have a footer at the bottom of the page scroll, and I wanted ti add it this way :

```
<ReactPageScroller ref={r => this.reactPageScroller = r} pageOnChange={this.onPageScroll}>
	<Page_1/>
	<Page_2/>
	<Page_3/>
	<Page_4/>
	<Page_5/>
	<Footer/>
</ReactPageScroller>
```
A workaround is to place footer at the bottom of `<Page_5/>`, but this is not as nice and it makes Page5 less lower.

**Comment by VikLiegostaiev** [comment]
@monkeydri in my opinion, if you want footer on the 5th page you should place it there not separately.

**Comment by monkeydri** [comment]
The thing is I would like to add a footer which "retracts itself", similarly to what can be done with [fullpage.js](https://github.com/alvarotrigo/fullPage.js) and I thought it could be achieved by adding the Footer as a page (child of ReactPageScroller) while using scrollUnavailable to animate back to penultimate page.

Also, it would be nice to have not full height pages but still be able to scroll to them with nice transition (where it sticks to the top of the page).

**Comment by VikLiegostaiev** [comment]
@monkeydri ok, maybe I understand you clearly. You want e.g. 1st section of the page be 80%, 2nd section be 20% and then, after scroll, there will be all 2nd section visible and 80% of 3rd section visible?

**Comment by monkeydri** [comment]
Yes exactly ! Thank you for your understanding. I should have made a drawing in the first place ;-)

**Comment by dharmabumzee** [comment]
Hi, is it possible to add footer at the end of the scroller and have its original size..not to have it extended to a full page?

<ReactPageScroller ref={c => (this.reactPageScroller = c)}>
          <FirstPage />
          <SecondPage />
          <ThirdPage />
          <Footer />
 </ReactPageScroller>

Beautiful job, btw!

<img width="906" alt="Screen Shot 2020-02-10 at 11 32 47 AM" src="https://user-images.githubusercontent.com/28141779/74142418-2224d300-4bf9-11ea-8c42-a3c80244d0cc.png">

**Comment by dharmabumzee** [comment]
For example, in App.js I tried this. The menu on top, a separate wrapper for all components that uses a react-page-scroller and footer at the end. But I can't get to the footer. It stops at the last component from AppPageScrollWrapper. Thanks in advance!

      <MenuAppBar />
      <AppPageScrollWrapper />
      <Footer />

**Comment by rheng001** [comment]
@VikLiegostaiev Any update on this feature? Would be really awesome to have this.

**Comment by wilsonych** [comment]
I tried to implement this feature. I am not sure if this is a good practice but at least it work. #84

**Comment by VikLiegostaiev** [comment]
hi all! sorry for such a long delay. adaptive height should be available in [new release](https://github.com/VikLiegostaiev/react-page-scroller/releases/tag/2.3.0)
