### ISSUE TITLE
UX Collision with other UI scrollable elements

### ISSUE THREAD

**Issue by EduardoHidalgo** [VikLiegostaiev/react-page-scroller#14]
I have a Google Map div in mi page, this UI element contain a lot of events attached like "onMouseOver", "MouseScroll", "MouseClick", etc.

When i try to interact with my google map using scroll, obviusly this interfers with "react-page-scroller" scroll event and both of them works when i scroll.

I need a way to turn off your page scroller component, or something such like that.

**Comment by VikLiegostaiev** [comment]
Hi @EduardoHidalgo, sorry for big delay. Can you please add event.stopPropagation() in your callback "MouseScroll" ?

**Comment by EduardoHidalgo** [comment]
It works perfectly. Thank you. You can close this issue.

**Comment by VikLiegostaiev** [comment]
@EduardoHidalgo You're welcome :-)
