### ISSUE TITLE
PageScroller doesn't render all child components

### ISSUE THREAD

**Issue by EduardoHidalgo** [VikLiegostaiev/react-page-scroller#15]
I have 7 components inside mi ScrollPage Component. When i'm in the web page, initially only render 2 components, if i scroll down, the next component will appear.

Example of my code of PageScroller
![image](https://user-images.githubusercontent.com/30780192/48487154-5984b400-e7eb-11e8-9aa3-cf3b96c6e299.png)

example of wrap elements. it just rendering 2 components at the beginning.
![image](https://user-images.githubusercontent.com/30780192/48486963-e3804d00-e7ea-11e8-9b43-bc61f36c9d72.png)

if i scroll, the next component will appear. As you can see, the last component is "Productos", where the last one should be "Contacto".
![image](https://user-images.githubusercontent.com/30780192/48487270-b2ece300-e7eb-11e8-9232-dda42f330c8e.png)

**I need to render all components at the beginning, How can i approach that?**

You can see the web site in this url: https://webmarina.now.sh/
and the code in this github repository: https://github.com/MarinaVVsoftware/WebMarina

**Comment by EduardoHidalgo** [comment]
I just gonna try to resolve it. I think if i use a react stateful class or the new react tool "hooks" i can force to render my components, or at least update his states whenever they are rendered.

If i solve the issue i will share you :D

**Comment by VikLiegostaiev** [comment]
hi @EduardoHidalgo, sorry for big delay.
That's was my feature, provided in this component, that new sections are rendered when user needs them. Just for improved user experience. I can add a new prop to render all sections at once. Is it ok for you?

**Comment by EduardoHidalgo** [comment]
It's bad because if some section are not rendered at first load, google web crawlers can't index content properly. But, if your library are used in client-side, it doesn't matter. React can't render her virtual DOM before render html. 

So, i really appreciate If you can add some way to render all sections at once <3

**Comment by VikLiegostaiev** [comment]
@EduardoHidalgo ok I will add a new prop for this.

**Comment by TemaGeographer** [comment]
@VikLiegostaiev also waiting for this feature to be added!

**Comment by VikLiegostaiev** [comment]
Hi guys, sorry for such big pause in maintaining, I am planning to do the major release this week, so I will update all the codebase.

**Comment by gugamaxara** [comment]
> Hi guys, sorry for such big pause in maintaining, I am planning to do the major release this week, so I will update all the codebase.

waiting so much... thanks

**Comment by VikLiegostaiev** [comment]
Hey. I hope it is fixed now, I've added `renderAllPagesOnFirstRender` flag. check here: https://github.com/VikLiegostaiev/react-page-scroller/releases/tag/2.0.0-beta
