### ISSUE TITLE
Issue Passing Props to Children Inside of ReactPageScroller

### ISSUE THREAD

**Issue by daniellehoo** [VikLiegostaiev/react-page-scroller#16]
Hello, I am having an issue updating the state of child components inside of the Page Scroller. Initial props will pass to the children, but then they will not update dynamically. I saw the closed issue #8 on this, but it seems that the updated code may have not solved the problem. Thank you.

**Comment by VikLiegostaiev** [comment]
Hi sorry for the delay, what version are you using?

**Comment by daniellehoo** [comment]
I am using 1.4.2

**Comment by ivajo26** [comment]
i have a same problem

**Comment by VikLiegostaiev** [comment]
hey, check here pls: https://github.com/VikLiegostaiev/react-page-scroller/releases/tag/2.0.0-beta
