### ISSUE TITLE
[Question] Can this be implemented using <a> tag instead of the pager from react-bootstrap?

### ISSUE THREAD

**Issue by leizleho** [VikLiegostaiev/react-page-scroller#17]
Hi,
I have a link on page 1 using <a href=#>Page 4</a>.  How can I make it go to page 4?
Currently, I am using this on my navigation bar using the Pager from react-bootstrap, however I am having hard time understanding how I can use this with just the <a> tag.

<ReactPageScroller ref={r => this.reactPageScroller = r} pageOnChange={this.onPageScroll}>
	<Page1/>
	<Page2/>
	<Page3/>
	<Page4/>
	<Page5/>
	<Footer/>
</ReactPageScroller>

Thank you,
Leizle

**Comment by VikLiegostaiev** [comment]
Hi @leizleho ,
You can go to page 4 from page 1 with the help of goToPage method, you can use it through ref.
You can find here an example of using goToPage: https://github.com/VikLiegostaiev/react-page-scroller/blob/master/demo/src/FullPage.js
