### ISSUE TITLE
Page scrolls down after last component

### ISSUE THREAD

**Issue by i-Living** [VikLiegostaiev/react-page-scroller#2]
Hello!
If you clicked on last page in navbar and then scroll down, page scroll down even after last component.

**Comment by VikLiegostaiev** [comment]
@i-Living Hi! Thanks for your report! I will take a look.

**Comment by VikLiegostaiev** [comment]
@i-Living  bug fixed. Can you take a look? https://github.com/VikLiegostaiev/react-page-scroller/tree/1.1.8
