### ISSUE TITLE
only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by manosindh** [VikLiegostaiev/react-page-scroller#20]
only one instance of babel-polyfill is allowed - error is thrown

**Comment by imalextu** [comment]
it's cauesd by both your project and react-page-scroller include babel-polyfill , and bebel-polyfill can only imported once ,  you can change them to Idempotent Babel Polyfill can be imported multiple times.you can see this:https://github.com/babel/babel-loader/issues/401

**Comment by johhansantana** [comment]
hey @imalextu I am using nextjs and I have this problem. Do you know what webpack config do I need to fix this?

I commented https://github.com/VikLiegostaiev/react-page-scroller/blob/a9df99486d1933b0ad1140e31f2de167d3423ad1/src/index.js#L2 on my `node_modules` and it works but I don't see anywhere else in my code where `babel-polyfill` is being imported.
