### ISSUE TITLE
Cannot read property 'goToPage' of null

### ISSUE THREAD

**Issue by rusinowiczjakub** [VikLiegostaiev/react-page-scroller#21]
I have a problem with goToPage method called on page scroller.
I have done everything like in example and it's still not working...

`
import React, {Component} from 'react';
import './App.scss';
import Header from "./Component/Header/Header";
import ReactPageScroller from "react-page-scroller";
import Navigation from "./Component/Navigation/Navigation";

class App extends Component {

    constructor(props) {
        super(props);
        this.reactPageScroller = null;
    }

    goToPage = (pageNumber) => {
        this.reactPageScroller.goToPage(pageNumber);
    };

    render() {
        return (
            <>
                <div>
                    <button onClick={this.goToPage(1)}>Test</button>
                    <Navigation/>
                    <ReactPageScroller ref={e => {this.reactPageScroller = e }}>
                        <Header/>
                        <div>
                            tt
                        </div>
                    </ReactPageScroller>
                </div>
            </>
        );
    }
}

export default App;
`

it's giving me an error:

> TypeError: Cannot read property 'goToPage' of null 

and it refers to this:
`
    goToPage = (pageNumber) => {
        this.reactPageScroller.goToPage(pageNumber);
    };
`

**Comment by VikLiegostaiev** [comment]
Hi @rusinowiczjakub 
In my doc all is ok. You made a mistake in calling the callback. 
`<button onClick={this.goToPage(1)}>Test</button>` should be for example:
`<button onClick={() => this.goToPage(1)}>Test</button>`.
Try it ;-) 
also you can modify class property: 
`goToPage = (pageNumber) => {
    this.reactPageScroller.goToPage(pageNumber);
};` to 
`goToPage = (pageNumber) => () => {
    this.reactPageScroller.goToPage(pageNumber);
};`

**Comment by rusinowiczjakub** [comment]
Thank you so much that's work!

**Comment by Giasinit** [comment]
mhmh

**Comment by Giasinit** [comment]
The implementation has completely changed. Now, you need to pass the page number through the prop `customPageNumber={this.state.page}` and set it to your desired page number. The fun part is that you only need to change the value of this variable to an integer, and it automatically updates the page!

So, there’s no need for a ref since the component does not support it. This is the only solution :)
