### ISSUE TITLE
Suggestions: add few features and fix Demo

### ISSUE THREAD

**Issue by PotLid** [VikLiegostaiev/react-page-scroller#22]
Thanks for awesome one-page scroll for React :) 
So far I am implementing your codes into my React project yet it would be better if I can set a custom className to component as well as I found that the Pager component from React-Bootstrap isn't working anymore. For my case I fixed this issue with latest Bootstrap-react's Nav and NavLink components.
Thanks for reading :)

**Comment by PotLid** [comment]
Actually I just modified your code as now I can set certain pages which allows normal scroll, and moving to adjacent pages after those scroll position reaches Top or Bottom section of the pages. Great plugins again. Thanks :)

**Comment by VikLiegostaiev** [comment]
@PotLid thank you. sorry, so busy now, do not have time to respond.
