### ISSUE TITLE
scrollWindowUp & Down firing after components unmounted as well as prohibiting touch move after unmount

### ISSUE THREAD

**Issue by PotLid** [VikLiegostaiev/react-page-scroller#24]
+ On my React projects, I found, with React-Router-Dom, when move between pages with one page scroll and without the plugins, it causes a random touch moves blockage on mobile devices ( confirmed both iPhoneX and iPad Pro ). I noticed that preventDefault for ontouchmove causes this issue, so added snippet which return it into its original state ( enable touch move ) when component is getting unmounted. 

+ I added isMounted flags in order to prevent scroll methods are fired even after the component is unmounted. On console, it shows me already fired events kept trying to change its unmounted component's state.

**Comment by PotLid** [comment]
#25

**Comment by VikLiegostaiev** [comment]
@PotLid thanks for pull request, merged, can I close?

**Comment by PotLid** [comment]
@VikLiegostaiev, sure :)
