### ISSUE TITLE
How to jump to a component without scrolling

### ISSUE THREAD

**Issue by aeh1307** [VikLiegostaiev/react-page-scroller#29]
Hi, is it possible to jump to another component without scrolling? I've managed to make the react page scroller work, but also need the page to be able to navigate directly to another component when clicking an element.  Any suggestions?

**Comment by VikLiegostaiev** [comment]
Hi @aeh1307 , you have an example here: https://github.com/VikLiegostaiev/react-page-scroller/blob/master/demo/src/FullPage.js,
here is the visual representation:
https://vikliegostaiev.github.io/react-page-scroller/#/demos/fullpage (buttons on top)

you can use goToPage function to achieve your need :-)

**Comment by aeh1307** [comment]
Thanks for the links! I'm not quite sure how to do it when my navigating logo with paths is a imported stateless functional component. The component contains a svg with paths which shall send you to the different pages (scrollcomponents). Do I have to send in pageNumbers in the self closed component-tag somehow? :)

**Comment by VikLiegostaiev** [comment]
@aeh1307 pageNumbers is only variable which contains pages for bootstrap/Pager. You need to manually pass goToPage method using `ref`. And call this method on every path.

**Comment by aeh1307** [comment]
Thanks, made the navigation work now! Do you know if its possible that the click triggers the pagecontent to show instantly, rather than one seeing the page scrolling thorugh the components in between as seen in the demo?

**Comment by VikLiegostaiev** [comment]
@aeh1307 try to set animationTimer to 0

**Comment by aeh1307** [comment]
Thanks, it worked :)
