### ISSUE TITLE
wrong index reported on pageOnChange callback

### ISSUE THREAD

**Issue by mihaiserban** [VikLiegostaiev/react-page-scroller#3]
On key/mouse scroll page change the index reported via pageOnChange starts from 1...n
The goToPage uses 0 index based array

So if you call goToPage with index 1 goes to page 2 (correct) but reports index 1 on pageOnChange (incorrect, should be index 2).

**Comment by VikLiegostaiev** [comment]
Hello! Thanks for your report! Will take a look soon.

**Comment by mihaiserban** [comment]
Your example is fine, but breaks if you want to highlight the current page on the Pager

**Comment by VikLiegostaiev** [comment]
thanks, merged it. #4

**Comment by mihaiserban** [comment]
Can you please publish a new version to npm?

**Comment by VikLiegostaiev** [comment]
yes, sure, in 20 minutes.

**Comment by VikLiegostaiev** [comment]
@mihaiserban Done :-)
