### ISSUE TITLE
Feature to disable "jump" scrolling on mobile

### ISSUE THREAD

**Issue by gugamaxara** [VikLiegostaiev/react-page-scroller#33]
When i run website in mobile and start scrolling it jumps like in desktop version, for example in Google Chrome when i am trying to go up from down it refreshes page, it will be great feature if i be able to disable scroll "jumping" if website runs on mobile. Thanks

**Comment by VikLiegostaiev** [comment]
Hi @gugamaxara , can u provide me with example how it is working? e.g. some screen recording?

**Comment by gugamaxara** [comment]
> Hi @gugamaxara , can u provide me with example how it is working? e.g. some screen recording?

Hello, i solved it like this: 
`render(){
        if(this.isDesktop()){
            return(
                <div>
                    <NavigationMenu goToPage={this.goToPage}/>
                    <ReactPageScroller 
                    ref={c => this.reactPageScroller = c} 
                    animationTimer={400}
                    pageOnChange={this.handleActiveComponent}
                    >
                        <Main goToPage={this.goToPage}/>
                        <About/>
                        <Portfolio/>
                        <Contact ContactTl={this.ContactTl}/>
    
                    </ReactPageScroller>
                </div>
            )
        }
        else{
            return(
                <div onScroll={this.checkContactViewPort}>
                    <NavigationMenu goToPage={this.goToPage}/>
                    <Main/>
                    <About/>
                    <Portfolio/>
                    <VisibilitySensor onChange={this.onChange} partialVisibility={true}>
                        <Contact ContactTl={this.ContactTl}/>
                    </VisibilitySensor>
                </div>
            )
        }
        
    }`
to explain with words, when i was just normally scrolling from mobile my web page in Google Chrome it was jumping exactly the same as it jumps on mouse wheel on Desktop version

**Comment by gugamaxara** [comment]
![jump](https://user-images.githubusercontent.com/17852677/68666684-cb5a1f80-055d-11ea-9abf-9d74d99c8a36.png)
I solved like this,
to explain with words, when i was scrolling my web page from mobile in Google Chrome it was jumping exactly the same as it jump on mouse wheel on desktop version

**Comment by VikLiegostaiev** [comment]
Hi @gugamaxara . Is it still actual? as I don't understand the problem and going to close this one
