### ISSUE TITLE
renderAllPagesOnFirstRender not working

### ISSUE THREAD

**Issue by gugamaxara** [VikLiegostaiev/react-page-scroller#34]
Hello again,
I installed 2.0.0-beta version via npm but renderAllPagesOnFirstRender still not working, i also tried to found it in source code in node_modules/react-page-scroller but it is not available in package also

**Comment by VikLiegostaiev** [comment]
@gugamaxara are u funny or what? u are not able to write me private messages in my social networks asking me to do it asap, it is the open source, when I will have time I will take a look.

**Comment by gugamaxara** [comment]
> @gugamaxara are u funny or what? u are not able to write me private messages in my social networks asking me to do it asap, it is the open source, when I will have time I will take a look.

Hello again, 
First of all sorry if you feel uncomfortable, i just really need to fix it fast, i am trying to do it for whole day without success, that's why i decide to write to you.
Sorry again

**Comment by VikLiegostaiev** [comment]
u're right, I forgot to publish new built version, will do it today

**Comment by gugamaxara** [comment]
> u're right, I forgot to publish new built version, will do it today

Thanks

**Comment by VikLiegostaiev** [comment]
Hi @gugamaxara. pls update ur version to 2.0.1-beta, it should be fixed now

**Comment by gugamaxara** [comment]
Thanks,
It works now
