### ISSUE TITLE
Cannot use overflow: scroll;

### ISSUE THREAD

**Issue by Cryton2017** [VikLiegostaiev/react-page-scroller#37]
When i try to add overflow: scroll; to my pages, it starts to scroll the div on the page but then jumps to a previous page. It also seams to be calling the pageOnChange function when i try to scroll a div with overflow. Is there a work around for this?

**Comment by VikLiegostaiev** [comment]
Hi @Cryton2017 ,
Yes u can use blockScrollDown and blockScrollUp props.
