### ISSUE TITLE
Scroll on mobile not fixed

### ISSUE THREAD

**Issue by Shortdrinque** [VikLiegostaiev/react-page-scroller#39]
I've tried version 2.0.2 Beta but the issue #35 isn't fixed for me on either iOS or Android. Any suggestions how to fix this?

**Comment by VikLiegostaiev** [comment]
Seems, u're right, will look into this once again

**Comment by Shortdrinque** [comment]
Okay thank you very much

**Comment by Shortdrinque** [comment]
Any progress on this one? @VikLiegostaiev

**Comment by VikLiegostaiev** [comment]
@Shortdrinque have u checked locally? For me all works well since 2.0.2, just demo wasn't updated :\

**Comment by VikLiegostaiev** [comment]
@Shortdrinque now I updated demo as well. for me works well on Android. Next time, please, check locally before creating issue
