### ISSUE TITLE
[bug-request] pageOnChange option

### ISSUE THREAD

**Issue by Puvvl** [VikLiegostaiev/react-page-scroller#41]
Hello, the problem is that after the user has clicked on navigation it triggers **pageOnChange**, **pageOnChange** does not update the page value and returns current page to the callback. After few milliseconds (when scroll to page) it triggers again. 

That process leads to repeatedly state update.

Video: [vimeo link](https://vimeo.com/386675411)

**Comment by VikLiegostaiev** [comment]
Hi, @Puvvl . I put console.log in place where the pageOnChange is called and it is called as it should with useEffect hook when componentIndex is updated. On initial render it is called with 0. On page scroll it is called with array number of the page (starting from 0). If u badly setup redux storage and it updates slow it doesn't mean that there is bug in my lib, I am closing the issue as there is no bug with pageOnChange.
