### ISSUE TITLE
Scrollbar hidden

### ISSUE THREAD

**Issue by DKuziuk** [VikLiegostaiev/react-page-scroller#47]
Is it possible to enable simple scrollbar, or I can use only page numbers like in example?

**Comment by VikLiegostaiev** [comment]
Hi, I need to take a look if it is possible

**Comment by DKuziuk** [comment]
Hi, I mean i want to add scrollbar to the right side of my page like here: [https://www.tesla.com/](url) for example. And i don`t know howw to do that. My div with components has overflow hidden. So how can i change that? 
![image](https://user-images.githubusercontent.com/63237631/80685781-5f9a4d80-8ad0-11ea-8f45-2d09beee137b.png)

**Comment by DKuziuk** [comment]
Ok, i don`t need that already. Anyway, thanks for quick reply)
