### ISSUE TITLE
Call a method before scrolling

### ISSUE THREAD

**Issue by Thurstonjhon** [VikLiegostaiev/react-page-scroller#5]
Hi im trying to implement this with gsap, is there a way i can play tween before scrolling to a page? an example i think is an exit animation before scrolling to another component. Thanks!

**Comment by VikLiegostaiev** [comment]
Hi, I haven't used gsap, you want me to implement this method or you want just do it by yourself with my hint?

**Comment by Thurstonjhon** [comment]
Hi Thanks for the response, Probably wanted to do it myself with your hint.

**Comment by Thurstonjhon** [comment]
@VikLiegostaiev  Thanks!, i got it working great library by the way very helpful!
