### ISSUE TITLE
How to prevent horizontal swipe on Mobile Mode ?(chrome)

### ISSUE THREAD

**Issue by LEEJAEHYUB** [VikLiegostaiev/react-page-scroller#52]
I am testing the swipe in mobile mode on Chrome.

Swipe up and down is possible, and when swiping left and right, I want to prevent the page from scrolling. Is there a way?

I am currently using react-page-scroller and SwiperJS at the same time.

**Comment by PotLid** [comment]
If you mean that you want to stop scrolling getting triggered by horizontal swiping motion, you can add logics which limit event trigger threshold inside react-page-scroller component as basically the page-scroller only recognize changes in the y value of the touch coordinate on the screen. As long as there's a slight changes in y-position, it would fire scrolling action. 

Or, you meant that completely making inner contents still from any of gesture, you could set CSS overflow: hidden on its outer wrap. 

Hope this helps

**Comment by LEEJAEHYUB** [comment]
Thanks for the reply!

But even if I prevented wheel scrolling, I still had problems when I was still mobile...
But when I looked at the web page, it was solved!
