### ISSUE TITLE
Scroll only vertical not horizontal when using function pageOnChange

### ISSUE THREAD

**Issue by samadiftikhar770** [VikLiegostaiev/react-page-scroller#58]
Is there any way out to tackle this situation. I want to change the page number in react-page-scroller  only if on scroll vertical not horizontally

Example if I am using a trackpad I only want a vertical scroll on function pageOnChange .

**Comment by samadiftikhar770** [comment]
while using the trackpad I am horizontally swiping on the trackpad but it is taking me to the next section of the page I understand with a vertical swipe is fine but not horizontal.

**Comment by samadiftikhar770** [comment]
https://codesandbox.io/s/modest-lamport-5yjbb?fontsize=14&hidenavigation=1&theme=dark

In this example, u can check using trackpad

**Comment by samadiftikhar770** [comment]
Anyone can help me with this bug

**Comment by VikLiegostaiev** [comment]
hey @samadiftikhar770 I am aware of this problem. Even when you are swiping horizontally you are calling vertical event. I almost done with fix, will try to release today or max in few days.

**Comment by samadiftikhar770** [comment]
@VikLiegostaiev  Thanks for responding. i will wait for the update.

**Comment by VikLiegostaiev** [comment]
@samadiftikhar770 can you try with react-page-scroller@2.0.8-beta?

**Comment by samadiftikhar770** [comment]
i have run this command 

npm install react-page-scroller@2.0.8-beta  --save

and check it on my project got this error 
Failed to compile.

./node_modules/react-page-scroller/es/index.js
Module not found: Can't resolve 'babel-polyfill' in 'F:\NimbusCorpWebsite\node_modules\react-page-scroller\es'

**Comment by VikLiegostaiev** [comment]
sorry for that, pls try with react-page-scroller@2.0.9-beta

**Comment by samadiftikhar770** [comment]
Thanks @VikLiegostaiev  This work now .
