### ISSUE TITLE
[issue] pageOnChange triggers after completion of page change is there any possibility that both things happen parallel.  

### ISSUE THREAD

**Issue by samadiftikhar770** [VikLiegostaiev/react-page-scroller#61]
I am using react page scroller in my reactjs project. I am facing the issue on scrolling . when I am scrolling page  it is triggering the pageOnChange function after completion of page scroll instead of triggering when scroll is happening.

**Step 1** 
Scrolled the mouse Wheel.
**Step 2**
Page starts sliding and taking to other page.
**Step 3** 
pageOnChange is triggered.

**What I want is :**
When I scroll pageOnChange triggered at same time . not after the completion of scroll process

**Comment by samadiftikhar770** [comment]
@VikLiegostaiev  can u help me with this is there any way to tackle this situation using react-page-scroller . i am stuck  in my project due to this .

**Comment by VikLiegostaiev** [comment]
@samadiftikhar770 related to #40

**Comment by samadiftikhar770** [comment]
@VikLiegostaiev  thanks waiting  for update on  callback function

**Comment by VikLiegostaiev** [comment]
hey, added callback `onBeforePageScroll`

**Comment by samadiftikhar770** [comment]
thanks
