### ISSUE TITLE
How to use with react hooks ref useRef?

### ISSUE THREAD

**Issue by hugoh59** [VikLiegostaiev/react-page-scroller#62]
I get the following error when trying to use along with the new react hook ref.
`target Element not found`

**Comment by VikLiegostaiev** [comment]
@hugoh59 where do you want to append the ref? for which element? I am already using ref inside my implementation and in can't be overwritten.

**Comment by hugoh59** [comment]
I wanted to pass a ref prof to ReactPageScroller but it does not seem to be possible. Otherwise, I can't get my mind around how to make the ref work for using goToPage along with react hooks implementation of refs.

**Comment by VikLiegostaiev** [comment]
`goToPage` is in legacy props. You can't pass the ref now. You can pass `customPageNumber` through the props.

**Comment by hugoh59** [comment]
Ok I hadn't notice that! Thank you very much @VikLiegostaiev !
