### ISSUE TITLE
conflict with <a > tag !

### ISSUE THREAD

**Issue by Naughty13** [VikLiegostaiev/react-page-scroller#63]
Hi Guys, when I use "a href="#id" tag on sideBar to change the view to a component on the main page,  "a" tag does not work correctly.! do you have any solution for that?!

**Comment by VikLiegostaiev** [comment]
Hi @Naughty13 . Correct, because you need to change the page programmatically. It won't auto scroll based on anchor. When user clicks particular `<a>` element you need to call click event with slide number and pass that slide number in `customPageNumber` prop.

**Comment by Naughty13** [comment]
Hi @VikLiegostaiev  Thank you, Man! that's helpful <3
