### ISSUE TITLE
touchmove event not working on mobile browsers

### ISSUE THREAD

**Issue by andycoles** [VikLiegostaiev/react-page-scroller#65]
User cannot scroll past second slide on mobile devices. Please see PR for details: https://github.com/VikLiegostaiev/react-page-scroller/pull/64

**Comment by VikLiegostaiev** [comment]
Hi, @andycoles , thanks for your PR. Checked with android and chrome mobile both demos works like they should work. Gonna to check with iOS and safari.

**Comment by VikLiegostaiev** [comment]
Indeed, not working after second slide, thanks for finding the bug!

**Comment by andycoles** [comment]
Thank you for confirming and merging.
