### ISSUE TITLE
onBeforePageScroll does not work as expected

### ISSUE THREAD

**Issue by hugoh59** [VikLiegostaiev/react-page-scroller#67]
onBeforePageScroll fires multiple times during the scrolling and there are no way to find out when when the page starts scrolling and when it is done.

**Comment by VikLiegostaiev** [comment]
Hi @hugoh59 , I've just tested once again and `onBeforePageScroll` is called once before scroll occured with the index of next page in argument. Probably you are doing something wrong. Please, attach the reproduction here.

**Comment by VikLiegostaiev** [comment]
I believe it is called multiple times when you scroll two slides at once. There is [issue](https://github.com/VikLiegostaiev/react-page-scroller/issues/30) created on such behaviour. However, if `onBeforePageScroll` is called twice during one slide, attach the repro pls

**Comment by Semantisby** [comment]
onBeforePageScroll is missing from npm version

**Comment by VikLiegostaiev** [comment]
I've just tested with version [2.1.0](https://www.npmjs.com/package/react-page-scroller/v/2.1.0) - all works
