### ISSUE TITLE
Scrolling is not working on trackpad and also when scroll on any other device it sometimes scrolls sometimes dont scroll

### ISSUE THREAD

**Issue by samadiftikhar770** [VikLiegostaiev/react-page-scroller#68]
I am using this in my app while testing the app i have gone through the problem that when i am using trackpad and trying to scroll the page it doesn't call scroll event. 

And while using other devices like  on my desktop when i am scrolling it is glitchy sometimes it scrolls sometimes it doesn't scroll the page.

**Comment by samadiftikhar770** [comment]
I am stuck with issue i have to make my project live by 15 Nov and i am stuck with this issue now

**Comment by samadiftikhar770** [comment]
@VikLiegostaiev  scrolling stops functioning when i scroll using trackpad it stop callback for scroll and once use trackpad mouse scroll also stops functioning

**Comment by VikLiegostaiev** [comment]
Hi @samadiftikhar770 , in this issue you wrote that all work https://github.com/VikLiegostaiev/react-page-scroller/issues/58. How could it happen that now it doesn't work? 🙂 I have no relation to your project you have chosen this library by urself. I can take a look into this issue in few days. I don't have apple trackpad, but with touchpad all work as expected.

**Comment by samadiftikhar770** [comment]
@VikLiegostaiev  i agree with you that you have no relation with my project. If i know about the compatibility for this library then i should have tried other libraries. When my project is on finish line i started testing my app then i found these bugs which i shared with you . If you work on these then i guess your library will be much polished.
anyways i have created my own custom function for scrolling and and for touch screen as well .


Thanks :)

**Comment by VikLiegostaiev** [comment]
I will investigate it more thoroughly. Gonna to rewrite the library as there are some freezes indeed.
