### ISSUE TITLE
pageOnChange being called on endless loop

### ISSUE THREAD

**Issue by Anbazhaganraj** [VikLiegostaiev/react-page-scroller#69]
pageOnChange being called multiple times enlessly bcoz of that components gets rerendered multiple times

**Comment by VikLiegostaiev** [comment]
Hi, this is not a react-page-scroller problem. I've even recorded a video with demo example, where you can see, that all works as expected.

https://user-images.githubusercontent.com/21306005/110213943-8f5d7300-7ea2-11eb-8dcb-e7b95f335e55.mov

**Comment by julia-dizhak** [comment]
> pageOnChange being called multiple times enlessly bcoz of that components gets rerendered multiple times

I have the same problem
