### ISSUE TITLE
Not working with typescript

### ISSUE THREAD

**Issue by syedraahim** [VikLiegostaiev/react-page-scroller#78]
after running this command for adding types: npm i @types/react-page-scroller.

I am getting the following error : 
npm ERR! 404  '@types/react-page-scroller@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by VikLiegostaiev** [comment]
Hi, fixed in 2.2.1

**Comment by syedraahim** [comment]
Hello VikLiegostaiev,
Still getting the same error.
