### ISSUE TITLE
Page will be scrolled when trying to scroll a scrollable div

### ISSUE THREAD

**Issue by cynde** [VikLiegostaiev/react-page-scroller#86]
When I have scrollable div using overflow: scroll, it will scroll the page when I'm trying to scroll the div. How to prevent it?

**Comment by cynde** [comment]
can somebody help me for this?

**Comment by cynde** [comment]
nevermind, already figured it out

**Comment by raghurambachu** [comment]
> nevermind, already figured it out

could you please share what you you have done to solve this? it could be of great help

**Comment by cynde** [comment]
@raghurambachu @ishangupta01 Sorry, I didn't find any solution. I didn't use this library.
