### ISSUE TITLE
Installation Error on Next.JS

### ISSUE THREAD

**Issue by adarshSrivastava01** [VikLiegostaiev/react-page-scroller#88]
![image](https://user-images.githubusercontent.com/59641575/166979067-a9901df7-2f3f-4de5-ace0-23f8a4eec250.png)

**Comment by daancs** [comment]
I had the same error. Not recommended but I used `--force` and it worked anyway.

**Comment by daancs** [comment]
Maybe you could update it to match the latest react version? @VikLiegostaiev

**Comment by imluckyhussain** [comment]
Author should test in react latest version & upgrade the react package version in package.json

**Comment by adarshSrivastava01** [comment]
Closing this issue because of no work being done.

**Comment by adarshSrivastava01** [comment]
Closing this issue because of no work being done here.
