### ISSUE TITLE
React 18.2 version missmatch

### ISSUE THREAD

**Issue by marko1943** [VikLiegostaiev/react-page-scroller#92]
Hello, I'm running a project on React 18, and I noticed this won't install cleanly.
I got it to install with `--legacy-peer-deps flag`
`npm install react-page-scroller --save --legacy-peer-deps`

but I have yet to test its functionality.

Any chance to update to the latest React? I could do a PR if it's safe.

**Comment by wgruszczyk** [comment]
@VikLiegostaiev Do you plan to fix the dependency problem? I'm using the library with Docusaurus 3 and need to get that resolved. 

Thank you!

**Comment by VikLiegostaiev** [comment]
Release here https://www.npmjs.com/package/react-page-scroller/v/3.0.1
